# This file was generated by GoReleaser. DO NOT EDIT.
cask "devdash" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/devdash"]
    end
  end

  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "92399223f27a9fba6bb45d78fce0d4aa1e1f8e4c0dab4327b509a6db4f080f7f"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a40bf685876df0dc4adc53b9630b2612caf994e3ca9648d5c86885caf99e95c"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e9a2e9985c90b86a6d0490cef940e38bd3d8514fe40162f376c480beee4e75c5"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a578f2d0500949636a159fb4c44225d1be49205186d60feac4b534f4df7a1a32"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devdash"
  desc "What is running on this machine, grouped by git repository"
  homepage "https://github.com/dogauzun/devdash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devdash"

  # No zap stanza required
end
