# This file was generated by GoReleaser. DO NOT EDIT.
cask "devdash" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/devdash"]
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "2f262f9ca910e92a33b28510f766510d3154cedf6ed53678f1e435efc453bf5c"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c4aafdf1761ccecf717ff530aea361f24c795e092108f504757e236887179dc"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "62b9f6b02d566bf5f8d3402320e5e9d07483e9807079ad34a40e1fea82b3041e"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5d9d43be53722c0f52bcb4a86a77f1f198b9ad95de36cbf950318d0c520994b"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devdash"
  desc "What is running on this machine, grouped by git repository"
  homepage "https://github.com/dogauzun/devdash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devdash"

  # No zap stanza required
end
