# This file was generated by GoReleaser. DO NOT EDIT.
cask "devdash" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/devdash"]
    end
  end

  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "70265cbf31d932a3873c1a9321af475f2d41839429a16fd09b2b68be9d192f0e"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "22971af81bf356526784f002d62656d368b5ec7262133b1979120593fb5cb4e9"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1e05cac9ab9ae46c8d2f9b92efac21a92aeea09dbc4183db338f8279a324e528"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0fcee32a479ae99c45c3c2251f7e6693a4fd3e6b32b17d78efa5fef37e3e9a23"
      url "https://github.com/dogauzun/devdash/releases/download/v#{version}/devdash_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devdash"
  desc "What is running on this machine, grouped by git repository"
  homepage "https://github.com/dogauzun/devdash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devdash"

  # No zap stanza required
end
